os: Visual Studio 2015

environment:
  CURL_VER: 7.64.1
  CURL_SHA256: 9252332a7f871ce37bfa7f78bdd0a0e3924d8187cc27cb57c76c9474a7168fb3
  ZLIB_VER: 1.2.11
  ZLIB_SHA256: 4ff941449631ace0d4d203e3483be9dbc9da454084111f97ea0a2114e19bf066
  PEXPORTS_VER: 0.47
  PEXPORTS_SHA256: 51f4d90d0dac3beb6fb5f8a4193ee0fae45b60eecc2dfdb9012f89eedce95a7c

artifacts:
  - name: libcurl
    path: libcurl-$(CURL_VER)-WinSSL-zlib-x86-x64.zip

build_script:
  - call windows\build_curl.bat

test_script: true
