os: Visual Studio 2017

environment:
  matrix:
    - ARCH:                x86
      MINGW_VER:           5.0.2
      D_VERSION:           2.077.1

artifacts:
  - path: mingw-libs-$(MINGW_VER).zip
    name: mingwlibs

build_script:
  - call windows\build_mingw.bat

test_script: true
