# Learn more: https://aka.ms/yaml
variables:
  BRANCH: $[ coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranchName'], 'master') ]

jobs:
  - job: Build_LLD
    timeoutInMinutes: 120
    condition: true
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
      # NB: update windows/build_lld.sha256sums as well
      LLVM_VER: 9.0.0
      ARCH: x86
    steps:
      - template: .azure-pipelines/build-lld.yml

  - job: Build_LLD64
    timeoutInMinutes: 120
    condition: true
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
      # NB: update windows/build_lld.sha256sums as well
      LLVM_VER: 9.0.0
      ARCH: x64
    steps:
      - template: .azure-pipelines/build-lld.yml

  - job: Build_Mingw_libs
    timeoutInMinutes: 120
    condition: true
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
      # NB: update windows/build_mingw.sha256sums as well
      MINGW_VER: 7.0.0
      D_VERSION: 2.077.1
    steps:
      - template: .azure-pipelines/build-mingw-libs.yml

  - job: Build_curl
    timeoutInMinutes: 120
    condition: true
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
      # NB: update windows/build_curl.sha256sums as well
      CURL_VER: 7.68.0
      ZLIB_VER: 1.2.11
      PEXPORTS_VER: 0.47
    steps:
      - template: .azure-pipelines/build-curl.yml

  - job: Build_Docs
    condition: true
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/build-docs.yml

  - job: Build_Release
    dependsOn: Build_Docs
    timeoutInMinutes: 120
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
      HOST_DMD_VERSION: 2.088.0
    steps:
      - template: .azure-pipelines/build-winrelease.yml
