steps:
  - script: |
      export
    displayName: Print environment variables
  - checkout: self
    fetchDepth: 1
  - script: |
      git clone --branch $(BRANCH) https://github.com/dlang/dlang.org.git work/dlang.org
      git clone --branch $(BRANCH) https://github.com/dlang/dmd.git work/dmd
      git clone --branch $(BRANCH) https://github.com/dlang/phobos.git work/phobos
    displayName: clone repos
  - script: |
      cd work/dlang.org
      make -f posix.mak release
    displayName: Build docs
  - script: |
      mkdir -p work/docs
      zip -r work/docs/docs.zip work/dlang.org/web
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: docs
      targetPath: work/docs
    displayName: Publish artifacts
