# Github Action to verify the releases build by the current repo / the workflow
# defined in build_release_template.yml.

name: test_release

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_release:
    name: "Default release build"
    if: ${{ github.repository == 'dlang/installer' }}
    uses: ./.github/workflows/build_release_template.yml
    with:
      # Test master for now, could also be safe with stable
      release_branch: master

      # Empty = use the repository/branch that triggered the build
      installer_repo:
      installer_branch:

  validate_build:
    name: Validate results of build_release_template.yml
    needs: build_release

    strategy:
      fail-fast: false
      matrix:

        target:
          - {
            host: windows-latest,
            os: windows,
            build: dmd.master.windows.7z
          }
          - {
            host: macos-latest,
            os: osx,
            build: dmd.master.osx.tar.xz
          }
          - {
            host: ubuntu-latest,
            os: linux,
            build: dmd.master.linux.tar.xz
          }
          - {
            host: macos-10.15,
            os: freebsd,
            build: dmd.master.freebsd-64.tar.xz
          }

    runs-on: ${{ matrix.target.host }}

    env:
      OS: ${{ matrix.target.os }}
      BUILD: ${{ matrix.target.build }}

    steps:
      - name: Download generated releases from the artifacts
        id: download-release
        uses: actions/download-artifact@v2
        with:
          name: dmd-release

      - name: Clone installer repo
        uses: actions/checkout@v2
        with:
          path: installer

      - name: Check ${{ matrix.target.os }} artifacts
        id: check
        if: ${{ matrix.target.os != 'freebsd' }}
        shell: bash
        run: source ./installer/test/release/validate_release.sh

      - name: Check ${{ matrix.target.os }} artifacts in a VM
        if: ${{ matrix.target.os == 'freebsd' }}
        uses: cross-platform-actions/action@v0.3.1
        with:
          operating_system: freebsd
          version: 12.2
          environment_variables: OS BUILD
          shell: bash
          run: source ./installer/test/release/validate_release.sh

  validate_build_metadata:
    name: Validate outputs of build_release_template.yml
    runs-on: ubuntu-latest
    needs: build_release

    # Revisions built above
    env:
      DMD_REF: ${{ needs.build_release.outputs.dmd-revision }}
      PHOBOS_REF: ${{ needs.build_release.outputs.phobos-revision }}

    steps:
      - name: Check outputs
        shell: bash
        run: |
          set -eux

          # Check that revisions are set
          [ "$DMD_REF" != "" ]
          [ "$PHOBOS_REF" != "" ]
